on:
  workflow_dispatch:
jobs:
  job1:
    name: login into azure  
    runs-on: ubuntu-22.04
    steps:
      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.235adba8-43c9-4fe8-bd30-aa1b26ed7a01 }}
          tenant-id: ${{ secrets.cc79164b-2d13-4562-a58c-6926091da960 }}
          subscription-id: ${{ secrets.7f4a2f6b-c856-48b4-896f-fa3324cb8b2b }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
